SOURCES = 01-solving-linear-systems-with-gaussian-jordan-elimination.tex \
          02-determinant-minor-cofactor.tex \
          03-inverse-matrix-and-five-tangents-determine-a-conic.tex \
          04-jacobi-eigenvalue-algorithm.tex \
          linear-algebra.tex \
          eigenvalues-and-eigenvectors.tex \
          conic-general-to-standard-form.tex \
          standard-form-of-conics.tex \
          plotting-conic-in-general-form-1.tex \
          plotting-conic-in-general-form-2.tex

include ../Makefile