SOURCES = 01-solving-linear-systems-with-gaussian-jordan-elimination.tex \
          02-determinant-minor-cofactor.tex \
          03-inverse-matrix-and-five-tangents-determine-a-conic.tex \
          04-jacobi-eigenvalue-algorithm.tex \
          linear-algebra.tex

include ../Makefile